version: '3'

services:
  dashboard:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"


