version: '3'

services:
  dashboard:
    build: .
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://host.docker.internal:8080
    # For Linux hosts
    extra_hosts:
      - "host.docker.internal:host-gateway"

